
<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Sign Up</div>
                        <?php if (isset($alert)): ?>
                            <div class="alert alert-<?= $alert['type'] ?>" role="alert">
                                <?= $alert['message'] ?>
                            </div>
                        <?php endif; ?>
                        <div class="card-body">
                            <form action="" method="post">
                            <div class="form-group row">
                                    <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name</label>
                                    <div class="col-md-6">
                                        <input type="text" id="first_name" class="form-control" name="first_name" required autofocus>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
                                    <div class="col-md-6">
                                        <input type="text" id="last_name" class="form-control" name="last_name" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="username" class="col-md-4 col-form-label text-md-right">Username</label>
                                    <div class="col-md-6">
                                        <input type="text" id="username" class="form-control" name="username" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password" class="form-control" name="password" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="password2" class="col-md-4 col-form-label text-md-right">Re-type Password</label>
                                    <div class="col-md-6">
                                        <input type="password" id="password2" class="form-control" name="password2" required>
                                    </div>
                                </div>
                                <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                                    value='<?php echo $this->security->getToken() ?>'/>
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Sign Up
                                    </button>
                                    <?=$this->tag->linkTo(['login', 'Log In', 'class' => 'btn btn-link']);?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>