<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create New Folder</div>
                        <div class="card-body">
                            <?php $this->flash->output() ?>
                            <form action="" method="post">
                                <div class="form-group row">
                                    <label for="folder_name" class="col-md-4 col-form-label text-md-right">Folder Name</label>
                                    <div class="col-md-6">
                                        <input type="text" id="folder_name" class="form-control" name="folder_name" required autofocus>
                                    </div>
                                </div>
                                <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                                    value='<?php echo $this->security->getToken() ?>'/>
                                <div class="col-md-6 offset-md-4">
                                    <?=$this->tag->linkTo(['', 'Cancel', 'class' => 'btn btn-secondary']);?>
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
