<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Delete Folder</div>
                        <div class="card-body">
                            <?php $this->flash->output() ?>
                            <form action="" method="post">
                                <div class="form-group row">
                                    <div class="col-md-12 text-center">
                                        Are you sure you would like to delete the folder
                                        <strong><?= $folder_name ?></strong>?
                                    </div>
                                </div>
                                <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                                    value='<?php echo $this->security->getToken() ?>'/>
                                <div class="col-md-6 offset-md-4">
                                    <?=$this->tag->linkTo(['', 'Cancel', 'class' => 'btn btn-secondary']);?>
                                    <button type="submit" name="form-yes" class="btn btn-danger">Delete</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
